spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zipkin?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
    username: root
    password: root1@3$5^
    continue-on-error: false
    driver-class-name: com.mysql.cj.jdbc.Driver
  #  sleuth:
  #    enabled: false
  application:
    name: zipkin-server
    #解决 The bean 'characterEncodingFilter', defined in class path resource [zipkin/autoconfigure/ui/ZipkinUiAutoConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/HttpEncodingAutoConfiguration.class] and overriding is disabled.Action
    #原文链接：https://blog.csdn.net/weixin_43866295/article/details/88319860
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

zipkin:
  storage:
    type: mysql

#解决IllegalArgumentException: Prometheus requires that all meters with the same name have the same set of tag keys.
management:
  metrics:
    web:
      server:
        auto-time-requests: false
